		{if $sbtn eq "alla"}{assign var=sectc value=audioc}{assign var=sectu value=audiou}{assign var=sect value=audios}
		{elseif $sbtn eq "alli"}{assign var=sectc value=imagec}{assign var=sectu value=imageu}{assign var=sect value=images}
		{elseif $sbtn eq "allv"}{assign var=sectc value=videoc}{assign var=sectu value=videou}{assign var=sect value=videos}
		{/if}
		{if $sbtn eq "alla" or $sbtn eq "alli" or $sbtn eq "allv"}
		    <td colspan=2 class="pad_borderbottom"><span class="gr">{$adm_sorttxt}</span>
        		<a href="{$admin_url}/{if $smarty.request.categ ne ""}{$sectc}{elseif $smarty.request.user ne ""}{$sectu}{else}{$sect}{/if}{if $smarty.request.user ne ""}/{$smarty.request.user}{/if}{if $smarty.request.categ ne ""}/{$smarty.request.categ}{/if}/all{if $smarty.request.timesort eq ""}/all_time{else}/{$smarty.request.timesort}{/if}"><span class="{if $smarty.request.type eq "all" or $smarty.request.type eq ""}act{else}{/if}">{$adm_sortall}</span></a>{$myfiles_delim}
        		<a href="{$admin_url}/{if $smarty.request.categ ne ""}{$sectc}{elseif $smarty.request.user ne ""}{$sectu}{else}{$sect}{/if}{if $smarty.request.user ne ""}/{$smarty.request.user}{/if}{if $smarty.request.categ ne ""}/{$smarty.request.categ}{/if}/active{if $smarty.request.timesort eq ""}/all_time{else}/{$smarty.request.timesort}{/if}"><span class="{if $smarty.request.type eq "active"}act{else}{/if}">{$adm_sortactive}</span></a>{$myfiles_delim}
        		{if $btn eq "adm_audio"}<a href="{$admin_url}/{if $smarty.request.categ ne ""}{$sectc}{elseif $smarty.request.user ne ""}{$sectu}{else}{$sect}{/if}{if $smarty.request.user ne ""}/{$smarty.request.user}{/if}{if $smarty.request.categ ne ""}/{$smarty.request.categ}{/if}/auditions{if $smarty.request.timesort eq ""}/all_time{else}/{$smarty.request.timesort}{/if}"><span class="{if $smarty.request.type eq "auditions"}act{else}{/if}">{$adm_sortauditions}</span></a>{$myfiles_delim}{/if}
        		<a href="{$admin_url}/{if $smarty.request.categ ne ""}{$sectc}{elseif $smarty.request.user ne ""}{$sectu}{else}{$sect}{/if}{if $smarty.request.user ne ""}/{$smarty.request.user}{/if}{if $smarty.request.categ ne ""}/{$smarty.request.categ}{/if}/comments{if $smarty.request.timesort eq ""}/all_time{else}/{$smarty.request.timesort}{/if}"><span class="{if $smarty.request.type eq "comments"}act{else}{/if}">{$adm_sortcomm}</span></a>{$myfiles_delim}
        		<a href="{$admin_url}/{if $smarty.request.categ ne ""}{$sectc}{elseif $smarty.request.user ne ""}{$sectu}{else}{$sect}{/if}{if $smarty.request.user ne ""}/{$smarty.request.user}{/if}{if $smarty.request.categ ne ""}/{$smarty.request.categ}{/if}/date{if $smarty.request.timesort eq ""}/all_time{else}/{$smarty.request.timesort}{/if}"><span class="{if $smarty.request.type eq "date"}act{else}{/if}">{$adm_sortdate}</span></a>{$myfiles_delim}
        		<a href="{$admin_url}/{if $smarty.request.categ ne ""}{$sectc}{elseif $smarty.request.user ne ""}{$sectu}{else}{$sect}{/if}{if $smarty.request.user ne ""}/{$smarty.request.user}{/if}{if $smarty.request.categ ne ""}/{$smarty.request.categ}{/if}/favorited{if $smarty.request.timesort eq ""}/all_time{else}/{$smarty.request.timesort}{/if}"><span class="{if $smarty.request.type eq "favorited"}act{else}{/if}">{$adm_sortfav}</span></a>{$myfiles_delim}
        		<a href="{$admin_url}/{if $smarty.request.categ ne ""}{$sectc}{elseif $smarty.request.user ne ""}{$sectu}{else}{$sect}{/if}{if $smarty.request.user ne ""}/{$smarty.request.user}{/if}{if $smarty.request.categ ne ""}/{$smarty.request.categ}{/if}/featured{if $smarty.request.timesort eq ""}/all_time{else}/{$smarty.request.timesort}{/if}"><span class="{if $smarty.request.type eq "featured"}act{else}{/if}">{$adm_sortfeat}</span></a>{$myfiles_delim}
        		<a href="{$admin_url}/{if $smarty.request.categ ne ""}{$sectc}{elseif $smarty.request.user ne ""}{$sectu}{else}{$sect}{/if}{if $smarty.request.user ne ""}/{$smarty.request.user}{/if}{if $smarty.request.categ ne ""}/{$smarty.request.categ}{/if}/inactive{if $smarty.request.timesort eq ""}/all_time{else}/{$smarty.request.timesort}{/if}"><span class="{if $smarty.request.type eq "inactive"}act{else}{/if}">{$adm_sortinactive}</span></a>{$myfiles_delim}
        		<a href="{$admin_url}/{if $smarty.request.categ ne ""}{$sectc}{elseif $smarty.request.user ne ""}{$sectu}{else}{$sect}{/if}{if $smarty.request.user ne ""}/{$smarty.request.user}{/if}{if $smarty.request.categ ne ""}/{$smarty.request.categ}{/if}/inappropriate{if $smarty.request.timesort eq ""}/all_time{else}/{$smarty.request.timesort}{/if}"><span class="{if $smarty.request.type eq "inappropriate"}act{else}{/if}">{$adm_sortinapp}</span></a>{$myfiles_delim}
        		<a href="{$admin_url}/{if $smarty.request.categ ne ""}{$sectc}{elseif $smarty.request.user ne ""}{$sectu}{else}{$sect}{/if}{if $smarty.request.user ne ""}/{$smarty.request.user}{/if}{if $smarty.request.categ ne ""}/{$smarty.request.categ}{/if}/private{if $smarty.request.timesort eq ""}/all_time{else}/{$smarty.request.timesort}{/if}"><span class="{if $smarty.request.type eq "private"}act{else}{/if}">{$adm_sortpriv}</span></a>{$myfiles_delim}
        		<a href="{$admin_url}/{if $smarty.request.categ ne ""}{$sectc}{elseif $smarty.request.user ne ""}{$sectu}{else}{$sect}{/if}{if $smarty.request.user ne ""}/{$smarty.request.user}{/if}{if $smarty.request.categ ne ""}/{$smarty.request.categ}{/if}/public{if $smarty.request.timesort eq ""}/all_time{else}/{$smarty.request.timesort}{/if}"><span class="{if $smarty.request.type eq "public"}act{else}{/if}">{$adm_sortpub}</span></a>{$myfiles_delim}
        		<a href="{$admin_url}/{if $smarty.request.categ ne ""}{$sectc}{elseif $smarty.request.user ne ""}{$sectu}{else}{$sect}{/if}{if $smarty.request.user ne ""}/{$smarty.request.user}{/if}{if $smarty.request.categ ne ""}/{$smarty.request.categ}{/if}/ratings{if $smarty.request.timesort eq ""}/all_time{else}/{$smarty.request.timesort}{/if}"><span class="{if $smarty.request.type eq "ratings"}act{else}{/if}">{$adm_sortrate}</span></a>{$myfiles_delim}
        		<a href="{$admin_url}/{if $smarty.request.categ ne ""}{$sectc}{elseif $smarty.request.user ne ""}{$sectu}{else}{$sect}{/if}{if $smarty.request.user ne ""}/{$smarty.request.user}{/if}{if $smarty.request.categ ne ""}/{$smarty.request.categ}{/if}/responses{if $smarty.request.timesort eq ""}/all_time{else}/{$smarty.request.timesort}{/if}"><span class="{if $smarty.request.type eq "responses"}act{else}{/if}">{$fresp_txt30}</span></a>
        		{if $btn eq "adm_video"}{$myfiles_delim}<a href="{$admin_url}/{if $smarty.request.categ ne ""}{$sectc}{elseif $smarty.request.user ne ""}{$sectu}{else}{$sect}{/if}{if $smarty.request.user ne ""}/{$smarty.request.user}{/if}{if $smarty.request.categ ne ""}/{$smarty.request.categ}{/if}/recommended{if $smarty.request.timesort eq ""}/all_time{else}/{$smarty.request.timesort}{/if}"><span class="{if $smarty.request.type eq "recommended"}act{else}{/if}">{$adm_sortrecomm}</span></a>{/if}
        		{if $btn ne "adm_audio"}{$myfiles_delim}<a href="{$admin_url}/{if $smarty.request.categ ne ""}{$sectc}{elseif $smarty.request.user ne ""}{$sectu}{else}{$sect}{/if}{if $smarty.request.user ne ""}/{$smarty.request.user}{/if}{if $smarty.request.categ ne ""}/{$smarty.request.categ}{/if}/views{if $smarty.request.timesort eq ""}/all_time{else}/{$smarty.request.timesort}{/if}"><span class="{if $smarty.request.type eq "views"}act{else}{/if}">{$adm_sortviews}</span></a>{/if}
                    </td>
                {elseif $sbtn eq "adm_areq" or $sbtn eq "adm_ireq" or $sbtn eq "adm_vreq"}
            	    <td colspan=2 class="pad_borderbottom">
            		<table cellpadding=0 cellspacing=0 width="100%" border=0>
            		    <tr>
            			<td>
            			    <span class="gr">{$adm_reqsort1}</span>
            			    <a href="{$admin_url}/requests/{$smarty.request.type}/{$smarty.request.show}/all"><span class="{if $smarty.request.filter eq "all"}act{else}{/if}">{$adm_reqsort2}</span></a>{$myfiles_delim}
        			    <a href="{$admin_url}/requests/{$smarty.request.type}/{$smarty.request.show}/active"><span class="{if $smarty.request.filter eq "active"}act{else}{/if}">{$adm_reqsort3}</span></a>{$myfiles_delim}
        			    <a href="{$admin_url}/requests/{$smarty.request.type}/{$smarty.request.show}/closed"><span class="{if $smarty.request.filter eq "closed"}act{else}{/if}">{$adm_reqsort4}</span></a>
        			</td>
        			<td width="300"><form id="setview"><input type="hidden" name="viewmode" value="{$smarty.session.viewmode}"></form>
                    		    <table width="100%" cellpadding=0 cellspacing=0>
                        		<tr><td align="right"><a href="javascript:void(0)" onclick="ReverseViewMode(); ReverseContentDisplay('gridview'); ReverseContentDisplay('listview'); ReverseContentDisplay('gview'); ReverseContentDisplay('lview');"><span id="lview" {if $smarty.session.viewmode eq "list"}style="display: none;"{else}style="display: block;"{/if}>{$files_listview}</span><span id="gview" {if $smarty.session.viewmode eq "grid"}style="display: none;"{else}style="display: block;"{/if}>{$files_gridview}</span></a></td></tr>
                    		    </table>
                		</td>
        		    </tr>
        		</table>
            	    </td>
                {/if}
